version: "3.8"

services:
  website-prod:
    image: ghcr.io/mcesarczyk/personal-homepage-website:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: any
    environment:
      - NODE_ENV=production
      - API_URL=http://ph_backend-prod:5000
      - API_PREFIX=/api/v1
      - NEXT_PUBLIC_API_URL=http://ph_backend-prod:5000
      - NEXT_PUBLIC_API_PREFIX=/api/v1
    ports:
      - 4200:4200
    networks:
      - swarm

  admin-prod:
    image: ghcr.io/mcesarczyk/personal-homepage-admin:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://ph_backend-prod:5000
    ports:
      - 4300:80
    networks:
      - swarm

  backend-prod:
    image: ghcr.io/mcesarczyk/personal-homepage-backend:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 5
        window: 120s
    environment:
      - ENV=development
      - BACKEND_PORT=5000
      - PUBLIC_URL=http://localhost:4650
      - FRONTEND_URL=http://ph_website-prod:4200
      - ADMIN_URL=http://ph_admin-prod:80
      - DATABASE_URL=postgresql://postgres:postgres@ph_db:5432/postgres?schema=public
      - DIRECT_URL=postgresql://postgres:postgres@ph_db:5432/postgres?schema=public
      - JWT_SECRET=45280cf2e1532342450c73bd435598577636d9b536f2bc1e659dbf6f4f9e5bf8
    ports:
      - 5000:5000
    networks:
      - swarm

  migrator-prod:
    image: ghcr.io/mcesarczyk/personal-homepage-backend-migrator:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@ph_db:5432/postgres?schema=public
      - DIRECT_URL=postgresql://postgres:postgres@ph_db:5432/postgres?schema=public
    networks:
      - swarm

  db:
    image: postgres:13
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
    networks:
      - swarm

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  swarm:
    driver: overlay
    attachable: true

volumes:
  db-data:
